// @ts-check
import { defineConfig } from 'eslint-config-hyoban'

export default defineConfig(
  {
    lessOpinionated: true,
    ignores: ['**/*.md'],
    stylistic: false,
    formatters: false,
    react: true,
  },
  {
    rules: {
      'react/no-context-provider': 'off',
      'package-json/valid-package-def': 'off',
      'ts/no-use-before-define': 0,
      'react/no-missing-key': 'warn',
      'react-hooks-extra/no-direct-set-state-in-use-effect': 0,
      'no-restricted-syntax': 'off',
      'import/no-anonymous-default-export': 'off',
      eqeqeq: 'warn',

      'unicorn/no-useless-undefined': 0,
      'no-console': 'warn',
      'react/dom/no-missing-button-type': 0,
      'unicorn/prefer-math-trunc': 'off',
      'unicorn/prefer-dom-node-remove': 'off',
      'ts/no-unsafe-function-type': 'off',
      'no-empty': 'off',
      'ts/no-empty-object-type': 'warn',
      'unicorn/prefer-query-selector': 0,
      'regexp/no-super-linear-backtracking': 0,

      'regexp/no-useless-assertions': 0,
      'unicorn/no-new-array': 0,
      'ts/method-signature-style': 0,
      'unicorn/prefer-code-point': 'warn',
      'unicorn/no-object-as-default-parameter': 'warn',
      'unused-imports/no-unused-vars': 'warn',
      'react/no-unstable-default-props': 'off',
      'unicorn/prefer-regexp-test': 'warn',
      'no-unsafe-optional-chaining': 'warn',
      'unicorn/prefer-logical-operator-over-ternary': 'warn',
      'arrow-body-style': 0,
      'unicorn/no-array-callback-reference': 0,
      'prefer-regex-literals': 0,
      'regexp/optimal-quantifier-concatenation': 'warn',
      'unicorn/prefer-string-slice': 0,
      'array-callback-return': 0,
      'regexp/no-unused-capturing-group': 1,
      'unicorn/no-anonymous-default-export': 0,
      'unicorn/no-magic-array-flat-depth': 1,
      'react-refresh/only-export-components': 0,
      'react/no-clone-element': 0,
      'react/hooks-extra/no-direct-set-state-in-use-effect': 0,
      'react-hooks/set-state-in-effect': 0,
      'react-hooks/preserve-manual-memoization': 0,
      'react-hooks/refs': 0,
      'import/consistent-type-specifier-style': 'off',
      'node/prefer-global/process': 'off',
      'node/prefer-global/buffer': 'off',
      'ts/ban-ts-comment': 'off',
      'prefer-arrow-callback': 'off',
      'no-useless-return': 'off',
      'test/prefer-lowercase-title': 'off',
      'no-unneeded-ternary': 'off',
      'unicorn/number-literal-case': 'off',
      'no-cond-assign': 'warn',
      'no-restricted-globals': 'off',
      'dot-notation': 'off',
      'one-var': 'off',
      'prefer-promise-reject-errors': 'off',
      'no-alert': 'off',
      'react-google-translate/no-conditional-text-nodes-with-siblings': 'off',
      'react/no-unstable-context-value': 'off',
      'react-dom/no-dangerously-set-innerhtml-with-children': 'off',
      'react/no-use-context': 'error',
      'react-dom/no-flush-sync': 'off',
      'node/handle-callback-err': 'off',
      'eslint-comments/no-unlimited-disable': 'off',
      'antfu/no-top-level-await': 'off',
    },
  },

  {
    files: ['**/*.json'],
    rules: {
      'jsonc/sort-keys': 0,
    },
  },

  {
    files: ['**/*.yml', '**/*.yaml'],
    rules: {
      'yaml/plain-scalar': 0,
    },
  },

  {
    files: ['**/*/package.json', 'package.json'],
    rules: {
      'package-json/valid-package-def': 0,
      'package-json/valid-name': 0,
      'package-json/valid-package-definition': 0,
      'package-json/require-description': 0,
      'package-json/valid-dependencies': 0,
    },
  },
)
