export { RichEditor } from './components/RichEditor'
export { allNodes, builtinNodes, customNodes } from './config'
export { allEditNodes, customEditNodes } from './config-edit'
export { getResolvedEditNodes, setResolvedEditNodes } from './node-registry'
export type { RichEditorProps, RichEditorVariant } from './types'
