import { createViteConfig } from '../vite.shared';

export default createViteConfig({
  entry: {
    'index': 'src/index.ts',
    'modules/embed/index': 'src/modules/embed/index.ts',
    'modules/embed/node': 'src/modules/embed/node.ts',
    'modules/code-block/index': 'src/modules/code-block/index.ts',
    'modules/code-block/renderer': 'src/modules/code-block/renderer.tsx',
    'modules/link-card/index': 'src/modules/link-card/index.ts',
    'modules/link-card/renderer': 'src/modules/link-card/renderer.tsx',
    'modules/gallery/index': 'src/modules/gallery/index.ts',
    'modules/gallery/node': 'src/modules/gallery/node.ts',
    'modules/gallery/renderer': 'src/modules/gallery/renderer.tsx',
    'modules/code-snippet/index': 'src/modules/code-snippet/index.ts',
    'modules/code-snippet/node': 'src/modules/code-snippet/node.ts',
    'modules/code-snippet/renderer': 'src/modules/code-snippet/renderer.tsx',
    'modules/chat/index': 'src/modules/chat/index.ts',
    'modules/chat/node': 'src/modules/chat/node.ts',
    'modules/chat/renderer': 'src/modules/chat/renderer.tsx',
    'modules/alert/index': 'src/modules/alert/index.ts',
    'modules/alert/renderer': 'src/modules/alert/renderer.tsx',
    'modules/banner/index': 'src/modules/banner/index.ts',
    'modules/banner/renderer': 'src/modules/banner/renderer.tsx',
    'modules/image/index': 'src/modules/image/index.ts',
    'modules/image/renderer': 'src/modules/image/renderer.tsx',
    'modules/mention/index': 'src/modules/mention/index.ts',
    'modules/mention/renderer': 'src/modules/mention/renderer.tsx',
    'modules/ruby/index': 'src/modules/ruby/index.ts',
    'modules/ruby/renderer': 'src/modules/ruby/renderer.tsx',
    'modules/video/index': 'src/modules/video/index.ts',
    'modules/video/renderer': 'src/modules/video/renderer.tsx',
    'modules/mermaid/index': 'src/modules/mermaid/index.ts',
    'modules/mermaid/renderer': 'src/modules/mermaid/renderer.tsx',
    'modules/excalidraw/index': 'src/modules/excalidraw/index.ts',
    'modules/excalidraw/node': 'src/modules/excalidraw/node.ts',
    'modules/nested-doc/index': 'src/modules/nested-doc/index.ts',
    'modules/nested-doc/node': 'src/modules/nested-doc/node.ts',
    'modules/poll/index': 'src/modules/poll/index.ts',
    'modules/poll/node': 'src/modules/poll/node.ts',
    'modules/poll/renderer': 'src/modules/poll/renderer.tsx',
    'style-token/index': 'src/style-token-entry.ts',
    'style-token/styles': 'src/style-token-styles-entry.ts',
  },
  vanillaExtract: true,
});
